### ISSUE TITLE
Some component's CSS don't affect the editor styles

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-angular#238]
## Steps to reproduce

1.  Enable some manual decorators in your editor.
2.  Add the following styles to the component's style file:

```css
:host ::ng-deep .ck-button__toggle {
	border-radius: calc(var(--ck-border-radius)*3.5) !important;
}

:host ::ng-deep .ck-button__toggle__inner {
	border-radius: calc(var(--ck-border-radius)*3.5) !important;
}
```

## Expected result

![](https://user-images.githubusercontent.com/20988892/104197156-f4f22d80-5424-11eb-8964-964c078e8e08.png)

## Current result

![](https://user-images.githubusercontent.com/20988892/104197174-fb80a500-5424-11eb-883c-9e8e2b260425.png)

## Notes

Styles are applied properly after moving CSS to global styles.
