### ISSUE TITLE
How to set content default height or min-height

### ISSUE THREAD

**Issue by qwe852147** [ckeditor/ckeditor5-angular#36]
I had created Ckeditor textarea but its height is always one line height.
It is possible to set default height?

The result is following 
![image](https://user-images.githubusercontent.com/10329643/45744701-ba4fa000-bc31-11e8-9a1f-344b9e85bdff.png)

**Comment by ma2ciek** [comment]
It's answered here: https://stackoverflow.com/questions/46559354/how-to-set-the-height-of-ckeditor-5-classic-editor.

Please, make some research before reporting issues in the future :)

**Comment by ksuhiyp** [comment]
I've came across that question, it's not working by adding that css rule to the css file of the component that hosts the editor, Noting that it works when I add the rule n the browser console

**Comment by ma2ciek** [comment]
I'm sorry for the latest answer, Didn't want to be rude.

In fact, there're two ways to style the component.

First is via the global stylesheet and then this should work:

```css
.ck-editor__editable {
    min-height: 500px !important;
}
```

But if you want to have the style in the parent component, then you need to add `:host ::ng-deep` pseudo selectors before.

```css
:host ::ng-deep .ck-editor__editable {
    min-height: 500px !important;
}
```
